const InvoiceSchema = {
  name: 'Invoice',
  properties: {
    _id: 'string',
    id: 'int?',
    invoiceNo: 'string',
    invoiceDate: {type: 'date', default: new Date()},
    time: 'string?',
    custId: 'int?',
    email: 'string?',
    custCode: 'string?',
    partyName: 'string?',
    addressLine1: 'string?',
    addressLine2: 'string?',
    addressLine3: 'string?',
    addressLine4: 'string?',
    city: 'string?',
    state: 'string?',
    country: 'string?',
    pinCode: 'string?',
    grossAmt: {type: 'float?', default: 0.0},
    cgstAmt: {type: 'float?', default: 0.0},
    sgstAmt: {type: 'float?', default: 0.0},
    totalAmt: {type: 'float?', default: 0.0},
    grandTotolAmt: {type: 'float?', default: 0.0},
    roundOff: {type: 'float?', default: 0.0},
    discAmt: {type: 'float?', default: 0.0},
    agent: 'string?',
    remarks: 'string?',
    prefix: 'string?',
    isSyned: {type: 'bool', default: false},
    items: {type: 'list', objectType: 'SelectedItem'},
    addedBy: 'string?',
    addedOn: {type: 'date?', default: new Date()},
    gstNo: {type: 'string?', default: ''},
    phoneNo: {type: 'string?', default: ''},
    changedBy: 'string?',
    changedOn: 'date?',
  },
  primaryKey: '_id',
};

const SelectedItemSchema = {
  name: 'SelectedItem',
  properties: {
    itemId: 'int?',
    itemName: 'string?',
    HSNCode: 'string?',
    UOMID: 'int?',
    qty: 'int?',
    rate: 'float?',
    grossAmt: {type: 'float?', default: 0.0},
    disPer: {type: 'float?', default: 0.0},
    disAmt: {type: 'float?', default: 0.0},
    netAmt: {type: 'float?', default: 0.0},
    cgstPer: {type: 'float?', default: 0.0},
    cgstAmt: {type: 'float?', default: 0.0},
    sgstPer: {type: 'float?', default: 0.0},
    sgstAmt: {type: 'float?', default: 0.0},
    totalAmt: {type: 'float?', default: 0.0},
  },
};

export {SelectedItemSchema, InvoiceSchema};

export default InvoiceSchema;
